---
title: "DSC_EDA"
author: "Kyle Dillon"
date: "2025-11-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
install.packages("moments")
install.packages("RColorBrewer")
install.packages("tidyverse")
install.packages("patchwork")
install.packages("corrplot")
```


```{r}
library(moments)
library(RColorBrewer)
library(tidyverse)
library(patchwork)
library(corrplot)
```


```{r}
CleanedDataNew <- readRDS("CleanedDataNew1.rds")
```


```{r}
str(CleanedDataNew)
```



#Table 1
```{r}
sum_cat_var <- CleanedDataNew %>%
  select("Gender","Race","Country_of_Origin","Education_Level","Marital_Status", "Health_Insurance",
                  "Thyroid_Problem","Gallstones","Liver_Condition","Taking_Treatment_Anemia", "Blood_Cholesterol_Meds",
                  "Told_High_BP", "Told_High_BP_2", "Attempted_Weight_Loss_Past_Year", "BMI") %>%
  pivot_longer(cols = everything(), names_to = "Features", values_to = "Value") %>% 
  group_by(Features, Value) %>%
  summarise(Frequency = n(), .groups= "drop") %>% 
  group_by(Features) %>% 
  mutate(
    Percentage = round(Frequency / sum(Frequency) * 100, 2),
    Proportion = round(Frequency / sum(Frequency), 2)
    ) %>%
  ungroup()

sum_cat_var
```


#Table 2
```{r}
sum_con_var <- CleanedDataNew %>% 
  select("Age", "Household_Size", "Family_Income_to_Poverty_Ratio", "Total_Energy", "Total_Protein", 
         "Total_Carbs", "Total_Sugar", "Total_Fiber", "Total_Fat", "Total_Sat_Fat", "Total_Mono_Sat_Fat", 
         "Total_Poly_Sat_Fat", "Total_Cholesterol", "Total_Lycopene", "Total_Lutein_Zeaxanthin", 
         "Total_Thiamin", "Total_Riboflavin", "Total_Niacin", "Total_VitaminB6", "Total_Folic_Acid", 
         "Total_Folate_DFE", "Total_Choline", "Total_VitaminB12", "Total_VitaminC", "Total_VitaminK", 
         "Total_VitaminD", "Total_Calcium", "Total_Phosphorus", "Total_Magnesium", "Total_Iron", 
         "Total_Zinc", "Total_Copper", "Total_Sodium","Total_Potassium", "Total_Selenium", "Total_Caffeine",
         "Vitamin_E_Alpha_Tocopherol", "Added_Alpha_Tocopherol", "Retinol", "Vitamin_A", "Alpha_Carotene", 
         "Beta_Carotene", "Beta_Cryptoxanthin","Total_Folate", "Food_Folate", "Added_Vitamin_B12", "Theobromine", 
         "Alcohol", "Moisture", "Total_Plain_Water", "Iodine", "Plasma_Fasting_Glucose", "Insulin", "Glycohemoglobin", 
         "Sleep_Hours_Weekdays", "Sleep_Hours_Weekends", "Minutes_Moderate_LTPA", 
         "Minutes_Vigorous_LTPA", "Minutes_Sedentary_Activity",) %>%
  summarize(across(everything(),
                   list(
                     Mean = ~mean(.x, na.rm = TRUE),
                     Median = ~median(.x, na.rm = TRUE),
                     Min = ~min(.x, na.rm = TRUE),
                     Max = ~max(.x, na.rm = TRUE),
                     Sd = ~sd(.x, na.rm = TRUE),
                     Skew = ~skewness(.x, na.rm = TRUE),
                     Kurtosis = ~kurtosis(.x, na.rm = TRUE)
                   ), .names = "{col}_{fn}"
                   )) %>%
  pivot_longer(everything(),
               names_to = c("features", "Statistic"),
               names_sep = "_(?=[^_]+$)",
               values_to = "Value") %>%
  pivot_wider(names_from = Statistic, values_from = Value) %>% 
  mutate(across(where(is.numeric), ~round(.x, 2)))
sum_con_var
```


#Graph 1 (Distribution of Target Variable (BMI))
```{r}
#Distribution for the numeric BMI variable
p1 <- ggplot(CleanedDataNew, aes(x = BMXBMI)) +
  geom_histogram(fill = "#56B4E9", color = "black")+
  labs(
    title = "Distribution of BMI",
    x = "BMI",
    y = "Count"
  )+
  theme_minimal()

#Distribution for the binary BMI variable
p2 <- ggplot(CleanedDataNew, aes(x = factor(BMI), fill = factor(BMI))) +
  geom_bar(color = "black")+
  scale_fill_manual(values = c("#0072B2", "#E69F00"))+
  labs(
    title = "Distribution of BMI Binary",
    x = "BMI Category",
    y = "Count",
    fill = "BMI Category"
  )+
  theme_minimal()
  

mergeBMI = p1 + p2 + plot_layout(ncol = 1)
mergeBMI
```


#Graph 2 (Corrplot)
```{r}
nutrient_vars <- CleanedDataNew %>%
  select(`Total_Energy`, `Total_Protein`, `Total_Carbs`, Total_Sugar, Total_Fiber, Total_Fat, 
         Total_Sat_Fat, Total_Mono_Sat_Fat, Total_Poly_Sat_Fat, Total_Cholesterol, Vitamin_A, Retinol, 
         Alpha_Carotene, Beta_Carotene, Beta_Cryptoxanthin, Total_Folate, Total_Folate_DFE, Total_Folic_Acid, BMXBMI)
```




```{r}
corr_matrix <- cor(nutrient_vars, use = "complete.obs")

corrplot(corr_matrix,
         method = "color", 
         type = "upper", 
         tl.col = "black", 
         tl.srt = 45,
         addCoef.col = "black", 
         number.cex = 0.7)
```


#Graph 3 (Distribution of Macro and Micro Nutrients)
```{r}
Histogram <- function(data, feature, fill_color = "#377EB8") {
  ggplot(data, aes_string(x = feature))+
    geom_histogram(bins = 30, fill = fill_color, color = "black", na.rm = TRUE)+
    labs(
    title = paste(feature),
    x = feature,
    y = "Count"
  )+
  theme_minimal()
}

g1 <- Histogram(CleanedDataNew, "Total_Protein")
g2 <- Histogram(CleanedDataNew, "Total_Carbs")
g3 <- Histogram(CleanedDataNew, "Total_Fat")
g4 <- Histogram(CleanedDataNew, "Total_Plain_Water")
g5 <- Histogram(CleanedDataNew, "Vitamin_A")
g6 <- Histogram(CleanedDataNew, "Total_VitaminB6")
g7 <- Histogram(CleanedDataNew, "Total_VitaminB12")
g8 <- Histogram(CleanedDataNew, "Total_VitaminC")
g9 <- Histogram(CleanedDataNew, "Total_VitaminD")
g10 <- Histogram(CleanedDataNew, "Total_VitaminK")
g11 <- Histogram(CleanedDataNew, "Total_Calcium")
g12 <- Histogram(CleanedDataNew, "Total_Iron")
g13 <- Histogram(CleanedDataNew, "Total_Magnesium")
g14 <- Histogram(CleanedDataNew, "Total_Potassium")
g15 <- Histogram(CleanedDataNew, "Total_Sodium")
g16 <- Histogram(CleanedDataNew, "Total_Zinc")
g17 <- Histogram(CleanedDataNew, "Iodine")
g18 <- Histogram(CleanedDataNew, "Total_Selenium")


merge = g1 + g2 +g3 + g4 + g5 + g6 + g7 + g8 + g9 + g10 + g11 + g12 + g13 + g14 + g15 + g16 + g17 +g18 + plot_layout(ncol = 5)
merge
```


#Graph 4 (Scatter Plot)
```{r}
ggplot(CleanedDataNew, aes(x = Total_Fat, y = Total_Mono_Sat_Fat)) +
  geom_point(alpha = 0.5, na.rm = TRUE) +
  geom_smooth(method = "lm", color = "red")+
  labs(
    title = "Total Fat vs Total MonoSaturated Fat",
    x = "Total Fat",
    y = "Total MonoSat Fat")+
  theme_minimal()
```


#Grpah 5 (Box plot)
```{r}
ggplot(CleanedDataNew, aes(x = factor(BMI), y = Glycohemoglobin, fill = factor(BMI)))+
  geom_boxplot()+
  labs(
    title = "BMI vs Glycohemoglobin",
    x = "BMI",
    y = "Glycohemoglobin",
    fill = "BMI Category"
  )+
  scale_fill_manual(values = c("Unhealthy" = "#E69F00", "Healthy" = "#0072B2"))+
  scale_y_continuous(limits = c(0,20))+
  theme_minimal()
```



